### ISSUE TITLE
Wifi Not working

### ISSUE THREAD

**Issue by andwhy81GH** [lonacluka/HP-EliteBook-840-G6-Hackintosh#2]
how were you able to get the wifi in this working, I see you have the kext in the right spot, do I need to force kernel or anything else?

Also I happened to have an older 6th gen EFI backup that I used to initially install Catilina on this then copied your EFI over to get everything working, the funny thing is that the trackpad buttons worked with that config, I even tried moving the SSDT that you added to it but that just made the trackpad not work at all..

I wonder if you can pull the trackpad button setting from my other EFI to get the ones on this trackpad to work.

**Comment by lonacluka** [comment]
Can you check what wifi you have? This kext is for intel wifi. Whats your configuration or model number?

My recommendation is that you make fresh EFI and try to boot from that.

**Comment by andwhy81GH** [comment]
Same model as yours, I just used your efi folder and rebooted, are you
saying to reinstall a fresh copy of osx using your efi?

**Comment by lonacluka** [comment]
No, just use fresh EFI. I thought you copied over this files over your old EFI.
I dont know whats your issue, if you have the same hardware it should work. 

Try booting in verbose mode and see what errors you get.

**Comment by andwhy81GH** [comment]
Ok, for wifi what method did you use to install, I saw that you may have to
force kernel or somthing.

**Comment by andwhy81GH** [comment]
I literally copied your whole efi folder over to mine

**Comment by lonacluka** [comment]
I didn't do any of that. Try swapping Airportitlwm with itlwm. 
They have really good docs here:  https://openintelwireless.github.io/itlwm/Installation.html#itlwm

**Comment by andwhy81GH** [comment]
Yep, I figured it out, I swapped the two kexts and enabled it in
config.plist, then installed the utility..

So now we need to fix the trackpad buttons

Then this thing will be ready for daily OSX.

Did you have any issues going from 10.15.5 to 6 or 7,

Or did you update to big Sur?

**Comment by lonacluka** [comment]
I upgraded from Catalina to Big Sur with no issue. But then I did clean install of Big Sur trying to fix trackpad issues I have (buggy trackpad, on readme.md - last section).

Also disabling force touch will probably fix your trackpad issues. Ill add that note to readme.
