### ISSUE TITLE
Some Screen tearing with maximizing and minimizing

### ISSUE THREAD

**Issue by andwhy81GH** [lonacluka/HP-EliteBook-840-G6-Hackintosh#3]
How did you patch the Icpu? I am getting some screen tearing and wandering if its fulling supported and patched. If I run the Haven benchmark I only get around 7-11 fps. just wanted to know if that is normal for the 620 gpu.

**Comment by lonacluka** [comment]
If you have the same hardware everything should work perfectly.

https://dortania.github.io/OpenCore-Install-Guide/ this guide contains everything you need to know, and on my README page you can read everything I did.

Also this reddit post helped me find correct settings for my iGPU https://www.reddit.com/r/hackintosh/comments/hu46xm/fix_hdmi_port_and_possibly_others_not_working_on/

**Comment by andwhy81GH** [comment]
If you run the benchmark, what fps are you getting?

**Comment by lonacluka** [comment]
<img width="220" alt="Screenshot 2021-04-15 at 18 44 48" src="https://user-images.githubusercontent.com/69514506/114907035-f3b51000-9e1a-11eb-89ef-827160a0c562.png">

Same on this settings 7-12. Hope you didn't plan on gaming on this CPU :) 
But I dont get any screen tearing. Check if you have 3d acceleration working.
<img width="666" alt="Screenshot 2021-04-15 at 18 48 20" src="https://user-images.githubusercontent.com/69514506/114907399-51495c80-9e1b-11eb-9d56-26752c427b51.png">

Metal family... Google is your friend

**Comment by andwhy81GH** [comment]
No I was not planning on gaming, but expected a little better, my old
hackintosh with the Intel 4400 (6th gen i5) seemed better.

I'll check if it is registered as Metal.

**Comment by lonacluka** [comment]
I didnt put much thought to igpu performance (i dont do any video editing/gaming etc) but my config has igfxfw set to "2", so maybe you can investigate if you can get better performance with different config.

https://www.reddit.com/r/hackintosh/comments/gbg5ms/oopencores_igfxfw_and_apples_guc/
