### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by HydroCarbon** [lonacluka/HP-EliteBook-840-G6-Hackintosh#6]
I upgrade my BIOS to latest version
Set iGPU to 64MB in BIOS
Generate my own serial, UUID,etc
Disable Secure Boot
But I didn't change my SSD，when I try to install on my laptop，
it says IOPlatformPanicAction.
Does is because my laptop use Intel Optane？
![wx_camera_1625244392541](https://user-images.githubusercontent.com/30232379/124340127-86c54100-dbe5-11eb-971c-efd68d45ad50.jpg)

**Comment by HydroCarbon** [comment]
my laptop is 840 G6 with i7 CPU

**Comment by lonacluka** [comment]
My quick google search says it is not compatible with hackintosh.

Try booting without nvmefix.kext

**Comment by lonacluka** [comment]
optane is not compatible with hackintosh

**Comment by HydroCarbon** [comment]
@lonacluka Does it need to change my SSD?

**Comment by lonacluka** [comment]
yes
